# -*- coding: utf-8 -*-
"""py7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkLytfReCdUwbEobTzyN5p0D6w-rq-PZ
"""

#  Write a program to create a dictionary and demonstrate dictionary methods and iteration.

student = {
    "name": "goku",
    "age": 20,
    "course": "Python",
    "marks": 85
}

print("Dictionary:")
print(student)


print("\nKeys:")
print(student.keys())

print("\nValues:")
print(student.values())

print("\nItems:")
print(student.items())

print("\nUsing get():")
print("Name:", student.get("name"))
print("marks:- ", student.get("marks"))

student.update({"age": 21, "city": "Ahmedabad"})
print("\nAfter update:")
print(student)

removed_value = student.pop("marks")
print("\nAfter pop:")
print(student)

student.setdefault("grade", "A")
print("\nAfter setdefault:")
print(student)


print("\nIterating through keys:")
for key in student:
    print(key)

print("\nIterating through values:")
for value in student.values():
    print(value)

print("\nIterating through key-value pairs:")
for key, value in student.items():
    print(key, ":", value)